use_frameworks!

platform :ios, '9.0'

target 'RVFullscreenPopGesture_Example' do
  pod 'RVFullscreenPopGesture', :path => '../'

  target 'RVFullscreenPopGesture_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
  end
end
